"""Add seller profiles table

Revision ID: 56a221e436e1
Revises: 980f685f5758
Create Date: 2025-10-05 14:10:44.104558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a221e436e1'
down_revision = '980f685f5758'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
